DevelopmentAdmin:
  extensions:
    - EcommerceDevelopmentAdminDecorator
  allowed_actions:
    - 'ecommerce'

Member:
  extensions:
    - EcommerceRole

SiteTree:
  extensions:
    - EcommerceSiteTreeExtension

Payment:
  extensions:
    - EcommercePayment


Page_Controller:
  extensions:
    - EcommerceSiteTreeExtension_Controller

Money:
  extensions:
    - EcommerceMoney

EcommerceDatabaseAdmin:
  allowed_actions:
    - runTask


